version: "1.0"

stages:
  - "clone"
  - "build"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "dadsgarage/dadsgarage:0.3.5"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    stage: "build"
    image_name: "dadsgarage/dadsgarage:0.3.5"
    working_directory: "${{clone}}/src/docker"
    tag: edge
