name: Continuous Integration

on:
  - pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: dadsgarage/dadsgarage:0.2.2

    steps:
      - name: pre-commit
        run: |
          pre-commit install
          pre-commit run -a

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build src/docker -t dadsgarage:local
